import {
  Building2,
  Globe2,
  GraduationCap,
  HeartPulse,
  Hotel,
  HardHat,
  Handshake,
  Store,
  FileText,
  Layers,
  Sparkles,
  ShieldCheck,
  ClipboardCheck,
  PackageCheck,
  Wallet,
  Headphones,
  Truck,
  Award,
  Eye,
  Lightbulb,
  Target,
  Users,
  Briefcase,
  Factory,
  Wrench,
  Cog,
  ShoppingBag,
  Box,
  Package,
  Shield,
  Zap,
  Crown,
  Star,
  Gem,
  Landmark,
  School,
  Stethoscope,
  UtensilsCrossed,
  Hammer,
  Tractor,
  Leaf,
  Plane,
  Car,
  Ship,
  Building,
  Home,
  ClipboardList,
  FileDown,
  ArrowRight,
} from 'lucide-react'

export const ICON_OPTIONS = [
  { name: 'Building2', label: 'Corporate Building', icon: Building2 },
  { name: 'Building', label: 'Building', icon: Building },
  { name: 'Landmark', label: 'Government', icon: Landmark },
  { name: 'Globe2', label: 'Globe', icon: Globe2 },
  { name: 'GraduationCap', label: 'Education', icon: GraduationCap },
  { name: 'School', label: 'School', icon: School },
  { name: 'HeartPulse', label: 'Healthcare', icon: HeartPulse },
  { name: 'Stethoscope', label: 'Medical', icon: Stethoscope },
  { name: 'Hotel', label: 'Hospitality', icon: Hotel },
  { name: 'UtensilsCrossed', label: 'Hospitality Food', icon: UtensilsCrossed },
  { name: 'HardHat', label: 'Construction', icon: HardHat },
  { name: 'Hammer', label: 'Hammer', icon: Hammer },
  { name: 'Handshake', label: 'Partnership', icon: Handshake },
  { name: 'Store', label: 'SME Store', icon: Store },
  { name: 'ShoppingBag', label: 'Retail', icon: ShoppingBag },
  { name: 'FileText', label: 'Document', icon: FileText },
  { name: 'ClipboardCheck', label: 'Clipboard Check', icon: ClipboardCheck },
  { name: 'ClipboardList', label: 'Clipboard List', icon: ClipboardList },
  { name: 'Layers', label: 'Layers', icon: Layers },
  { name: 'Sparkles', label: 'Sparkles', icon: Sparkles },
  { name: 'ShieldCheck', label: 'Shield Check', icon: ShieldCheck },
  { name: 'Shield', label: 'Shield', icon: Shield },
  { name: 'PackageCheck', label: 'Package Check', icon: PackageCheck },
  { name: 'Package', label: 'Package', icon: Package },
  { name: 'Box', label: 'Box', icon: Box },
  { name: 'Wallet', label: 'Wallet', icon: Wallet },
  { name: 'Headphones', label: 'Support', icon: Headphones },
  { name: 'Truck', label: 'Delivery', icon: Truck },
  { name: 'Ship', label: 'Shipping', icon: Ship },
  { name: 'Plane', label: 'Air Freight', icon: Plane },
  { name: 'Car', label: 'Vehicle', icon: Car },
  { name: 'Award', label: 'Award', icon: Award },
  { name: 'Crown', label: 'Crown', icon: Crown },
  { name: 'Star', label: 'Star', icon: Star },
  { name: 'Gem', label: 'Gem', icon: Gem },
  { name: 'Eye', label: 'Vision', icon: Eye },
  { name: 'Lightbulb', label: 'Innovation', icon: Lightbulb },
  { name: 'Target', label: 'Target', icon: Target },
  { name: 'Users', label: 'Users', icon: Users },
  { name: 'Briefcase', label: 'Business', icon: Briefcase },
  { name: 'Factory', label: 'Factory', icon: Factory },
  { name: 'Tractor', label: 'Agriculture', icon: Tractor },
  { name: 'Wrench', label: 'Tools', icon: Wrench },
  { name: 'Cog', label: 'Operations', icon: Cog },
  { name: 'Zap', label: 'Energy', icon: Zap },
  { name: 'Leaf', label: 'Sustainability', icon: Leaf },
  { name: 'Home', label: 'Home', icon: Home },
  { name: 'FileDown', label: 'Download', icon: FileDown },
  { name: 'ArrowRight', label: 'Arrow', icon: ArrowRight },
] as const

export const ICON_MAP = Object.fromEntries(ICON_OPTIONS.map((o) => [o.name, o.icon])) as Record<string, typeof Building2>

export function getIconByName(name: string | null | undefined) {
  if (!name) return null
  return (ICON_MAP[name] ?? null) as unknown as typeof Building2 | null
}
